Repository snhuproduct/turbine, pull requests merged in 2022-08, with the labels that each got.

#32 Restructered group list table implementation
  apps/toboggan-app/src/app/group/components/group-list/group-list.component.ts
Labels: enhancement

#38 Snhut 1562 - Filter User Table to Active Users Only by Default
  apps/toboggan-app/src/app/shared/services/table-data/table-data.service.ts
  apps/toboggan-app/src/app/user/components/user-table/data/user-table-header.ts
  apps/toboggan-app/src/app/user/components/user-table/user-table.component.ts
Labels: enhancement

#40 Snhut 1242 group list frontend enhancements
  apps/toboggan-app/src/app/group/components/group-list/group-list.component.html
  apps/toboggan-app/src/app/group/components/group-list/group-list.component.ts
  apps/toboggan-app/src/app/group/components/group-list/group-table.type.ts
  apps/toboggan-app/src/app/group/pages/group-main-page/group-main-page.component.html
  apps/toboggan-app/src/app/group/pages/group-main-page/group-main-page.component.spec.ts
Labels: enhancement

#41 SNHUT-1562 - Remove Sorting from Status column
  apps/toboggan-app/src/app/user/components/user-table/data/user-table-header.ts
  apps/toboggan-app/src/app/user/components/user-table/user-table.component.html
  apps/toboggan-app/src/app/user/components/user-table/user-table.component.ts
  apps/toboggan-app/src/app/user/components/user-table/user-table.types.ts
  package-lock.json
  package.json
  yarn.lock
Labels: bug, enhancement

#35 SNHUT-1583 - User Management | User list - Frontend (QA) | E2E test coverage
  apps/toboggan-app-e2e/src/fixtures/users.json
  apps/toboggan-app-e2e/src/integration/users.spec.ts
  apps/toboggan-app-e2e/src/support/app.po.ts
Labels: enhancement

#36 SNHUT-1589- User Management | Deactivation success and error states - Frontend (QA)
  apps/toboggan-app-e2e/src/integration/users.spec.ts
Labels: enhancement

#52 Create group and add user to group modals refactoring using david's modal component
  apps/toboggan-api/src/providers/groups/groups.service.ts
  apps/toboggan-app/src/app/group/components/add-users/add-users.component.html
  apps/toboggan-app/src/app/group/components/add-users/add-users.component.spec.ts
  apps/toboggan-app/src/app/group/components/add-users/add-users.component.ts
  apps/toboggan-app/src/app/group/components/create-group/create-group.component.html
  apps/toboggan-app/src/app/group/components/create-group/create-group.component.spec.ts
  apps/toboggan-app/src/app/group/components/create-group/create-group.component.ts
  apps/toboggan-app/src/app/group/pages/group-main-page/group-main-page.component.html
  apps/toboggan-app/src/app/group/pages/group-main-page/group-main-page.component.spec.ts
  apps/toboggan-app/src/app/group/pages/group-main-page/group-main-page.component.ts
  apps/toboggan-app/src/app/shared/components/modal/modal.component.ts
Labels: enhancement

#48 SNHUT-1576 user management initiate user password reset backend
  apps/toboggan-api/src/controllers/users/users.controller.ts
  apps/toboggan-api/src/providers/users/users.service.ts
  yarn.lock
Labels: enhancement

#51 SNHUT-1237 - User Management | Initiate user password reset - Frontend (QA)
  apps/toboggan-app-e2e/src/integration/users.spec.ts
Labels: enhancement

#50 SNHUT-1562- User Management | User list demo fixes - Frontend (QA)
  apps/toboggan-app-e2e/src/integration/users.spec.ts
Labels: enhancement

#46 SNHUT-1575 - User Management | Search user list (Part 2)
  apps/toboggan-app-e2e/src/fixtures/users.json
  apps/toboggan-app-e2e/src/integration/users.spec.ts
Labels: enhancement

#44 SNHUT-1563 - User Management | User list pagination fixes - Frontend
  apps/toboggan-app-e2e/src/integration/users.spec.ts
Labels: enhancement

#25 SNHUT-1586, SNHUT-587 - Group Management | Create Group - Frontend | E2E test coverage
  README.md
  apps/toboggan-app-e2e/src/integration/group-main-page.spec.ts
Labels: enhancement

#39 SNHUT-1587 - Group Management | Add users to groups via create group modal - Frontend (QA)
  apps/toboggan-app-e2e/src/integration/group-main-page.spec.ts
Labels: enhancement

#54 SNHUT-1673: Editing new user does not update the table
  apps/toboggan-app/src/app/shared/services/user/user.service.ts
  apps/toboggan-app/src/app/user/components/edit-user/edit-user.component.ts
  apps/toboggan-app/src/app/user/components/user-table/user-table.component.ts
Labels: bug, enhancement

#57 SNHUT-582 - User Management | Password reset initiation success or error state - Frontend (Part 1) (QA)
  apps/toboggan-app-e2e/src/integration/users.spec.ts
Labels: enhancement

#31 SNHUT-1242 - Group Management | Group list - Frontend | E2E test coverage
  apps/toboggan-app-e2e/src/fixtures/groups.json
  apps/toboggan-app-e2e/src/integration/groups.spec.ts
  package.json
Labels: enhancement

#30 SNHUT-583 - User Management | Edit user - Frontend | E2E test coverage
  apps/toboggan-app-e2e/src/integration/edit-user.spec.ts
Labels: enhancement

#58 Reload on User Creation When Filter Set to Inactive
  apps/toboggan-app/src/app/group/components/create-group/create-group.component.ts
  apps/toboggan-app/src/app/shared/services/table-data/table-data.service.ts
  apps/toboggan-app/src/app/user/components/create-user/create-user.component.ts
  apps/toboggan-app/src/app/user/components/user-table/user-table.component.ts
Labels: bug

#60 [Fix] SNHUT-1242 - Group Management (QA)
  apps/toboggan-app-e2e/src/integration/groups.spec.ts
Labels: bug

#59 SNHUT-583 - User Management | Edit user - Frontend (QA)
  apps/toboggan-app-e2e/src/integration/users.spec.ts
Labels: enhancement

#61 SNHUT-1563 - User Management | User list pagination fixes - Frontend (QA)
  apps/toboggan-app-e2e/src/fixtures/users.json
  apps/toboggan-app-e2e/src/integration/users.spec.ts
Labels: enhancement
