Repository snhuproduct/turbine, pull requests merged in 2023-01, with the labels that each got.

#135 Snhut 2258 Staff Profile UI implementaion with mock endpoints
  apps/toboggan-api/src/app/app.module.ts
  apps/toboggan-api/src/staff-profile/staff-profile.controller.spec.ts
  apps/toboggan-api/src/staff-profile/staff-profile.controller.ts
  apps/toboggan-api/src/staff-profile/staff-profile.mock.ts
  apps/toboggan-api/src/staff-profile/staff-profile.module.ts
  apps/toboggan-api/src/staff-profile/staff-profile.service.spec.ts
  apps/toboggan-api/src/staff-profile/staff-profile.service.ts
  apps/toboggan-app/src/app/app-routing.module.ts
  apps/toboggan-app/src/app/staff-profile/components/contact-tab/contact-tab.component.html
  apps/toboggan-app/src/app/staff-profile/components/contact-tab/contact-tab.component.scss
  apps/toboggan-app/src/app/staff-profile/components/contact-tab/contact-tab.component.spec.ts
  apps/toboggan-app/src/app/staff-profile/components/contact-tab/contact-tab.component.ts
  apps/toboggan-app/src/app/staff-profile/components/personal-tab/personal-tab.component.html
  apps/toboggan-app/src/app/staff-profile/components/personal-tab/personal-tab.component.scss
  apps/toboggan-app/src/app/staff-profile/components/personal-tab/personal-tab.component.spec.ts
  apps/toboggan-app/src/app/staff-profile/components/personal-tab/personal-tab.component.ts
  apps/toboggan-app/src/app/staff-profile/pages/staff-profile-main-page/staff-profile-main-page.component.html
  apps/toboggan-app/src/app/staff-profile/pages/staff-profile-main-page/staff-profile-main-page.component.scss
  apps/toboggan-app/src/app/staff-profile/pages/staff-profile-main-page/staff-profile-main-page.component.spec.ts
  apps/toboggan-app/src/app/staff-profile/pages/staff-profile-main-page/staff-profile-main-page.component.ts
  apps/toboggan-app/src/app/staff-profile/pages/staff-profile-main.mock.ts
  apps/toboggan-app/src/app/staff-profile/services/staff-profile.service.spec.ts
  apps/toboggan-app/src/app/staff-profile/services/staff-profile.service.ts
  apps/toboggan-app/src/app/staff-profile/staff-profile-routing.module.ts
  apps/toboggan-app/src/app/staff-profile/staff-profile.module.ts
  libs/toboggan-common/src/lib/toboggan-common.ts
  libs/toboggan-constants/src/lib/toboggan-constants.ts
Labels: new feature

#137 SNHUT:3168-Activate - Deactivate User - Change Status API Integration…
  apps/toboggan-api/src/app/modules/users/users.controller.ts
  apps/toboggan-api/src/app/modules/users/users.service.ts
  apps/toboggan-app/src/app/shared/services/user/user.service.ts
  apps/toboggan-app/src/app/user/components/user-table/user-table.component.ts
Labels: enhancement

#146 Preview content for selected learning resource node
  .vscode/launch.json
  apps/toboggan-api/src/app/app.module.ts
  apps/toboggan-api/src/app/modules/content-management/content-management.controller.spec.ts
  apps/toboggan-api/src/app/modules/content-management/content-management.service.spec.ts
  apps/toboggan-api/src/app/modules/content-serving/content-serving.module.ts
  apps/toboggan-api/src/app/modules/content-serving/controller/content-serving.controller.spec.ts
  apps/toboggan-api/src/app/modules/content-serving/controller/content-serving.controller.ts
  apps/toboggan-api/src/app/modules/content-serving/service/content-serving.service.spec.ts
  apps/toboggan-api/src/app/modules/content-serving/service/content-serving.service.ts
  apps/toboggan-app/project.json
  apps/toboggan-app/src/app/app-routing.module.ts
  apps/toboggan-app/src/app/content-management/components/content-preview-button/content-preview-button.component.html
  apps/toboggan-app/src/app/content-management/components/content-preview-button/content-preview-button.component.scss
  apps/toboggan-app/src/app/content-management/components/content-preview-button/content-preview-button.component.spec.ts
  apps/toboggan-app/src/app/content-management/components/content-preview-button/content-preview-button.component.ts
  apps/toboggan-app/src/app/content-management/components/curriculum-pathway/curriculum-pathway.component.ts
  apps/toboggan-app/src/app/content-management/content-management.module.ts
  apps/toboggan-app/src/app/content-management/pages/content-management-main-page/content-management-main-page.component.html
  apps/toboggan-app/src/app/content-management/pages/content-management-main-page/content-management-main-page.component.scss
  apps/toboggan-app/src/app/content-management/pages/content-management-main-page/content-management-main-page.component.ts
  apps/toboggan-app/src/app/content-management/services/content-selection.service.spec.ts
  apps/toboggan-app/src/app/content-management/services/content-selection.service.ts
  apps/toboggan-app/src/app/content-serve/content-serve.module.ts
  apps/toboggan-app/src/app/content-serve/content-serve.routing.ts
  apps/toboggan-app/src/app/content-serve/pages/content-preview/content-preview.component.html
  apps/toboggan-app/src/app/content-serve/pages/content-preview/content-preview.component.scss
  apps/toboggan-app/src/app/content-serve/pages/content-preview/content-preview.component.spec.ts
  apps/toboggan-app/src/app/content-serve/pages/content-preview/content-preview.component.ts
  apps/toboggan-app/src/app/content-serve/services/content.service.spec.ts
  apps/toboggan-app/src/app/content-serve/services/content.service.ts
  libs/toboggan-common/src/lib/toboggan-common.ts
  package-lock.json
  package.json
  tsconfig.base.json
Labels: new feature

#150 Updated SSO Endpoint for SessionId
  apps/toboggan-api/src/app/modules/auth/http-header-strategy.service.ts
Labels: enhancement, new feature

#158 Create an endpoint for fetching latest session id of user
  apps/toboggan-api/src/app/modules/auth/http-header-strategy.service.ts
  apps/toboggan-api/src/app/modules/authentication/authentication.controller.spec.ts
  apps/toboggan-api/src/app/modules/authentication/authentication.controller.ts
  apps/toboggan-api/src/app/modules/authentication/authentication.module.ts
  apps/toboggan-api/src/app/modules/authentication/authentication.service.ts
Labels: enhancement
